title: Ilker Demirel
email: demirel@mit.edu
description: >-
  Ilker Demirel is a PhD student at MIT CSAIL advised by David Sontag in the ClinicalML group.

url: "https://demireal.github.io"
baseurl: ""

markdown: kramdown
permalink: pretty

include:
  - _pages

plugins:
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
